// MUST be kept in line with the colors of the css classes
export const METRIC_THEME_CHART_PALETTE_COLORS = {
  CHART_PALETTE_COLOR_1: "#00a8e8",
  CHART_PALETTE_COLOR_2: "#e76500",
  CHART_PALETTE_COLOR_3: "#a24600",
  CHART_PALETTE_COLOR_4: "#2e17e7",
  CHART_PALETTE_COLOR_5: "#2010a2",
};

export const METRIC_THEME_CHART_PALETTE_CLASSES = {
  CHART_PALETTE_COLOR_1: "chart-palette-1",
  CHART_PALETTE_COLOR_2: "chart-palette-2",
  CHART_PALETTE_COLOR_3: "chart-palette-3",
  CHART_PALETTE_COLOR_4: "chart-palette-4",
  CHART_PALETTE_COLOR_5: "chart-palette-5",
};

export const METRIC_THEME_FONT_COLORS = {
  PRIMARY_TEXT: "#2e384d",
  SECONDARY_TEXT: "#8798ad",
};

export const METRIC_THEME_FONT_COLOR_CLASSES = {
  PRIMARY_TEXT: "dark-gray-text-primary",
  SECONDARY_TEXT: "light-gray-text-secondary",
};

export const METRIC_THEME_FONT_WEIGHT_CLASSES = {
  PRIMARY: "font-inter-light-500",
  SECONDARY: "font-inter-light-300",
};

export const METRIC_THEME_DATA_BLOCK_FONT_PROPERTY_CLASSES = {
  HEADER: "metric-block-header-text",
  CONTENT: "metric-block-content-text",
  FOOTER: "metric-block-footer-text",
};

export const METRIC_THEME_CHART_FONT_CLASSES = {
  PRIMARY: `${METRIC_THEME_FONT_WEIGHT_CLASSES.PRIMARY} ${METRIC_THEME_FONT_COLOR_CLASSES.PRIMARY}`,
  SECONDARY: `${METRIC_THEME_FONT_WEIGHT_CLASSES.SECONDARY} ${METRIC_THEME_FONT_COLOR_CLASSES.SECONDARY}`,
};

export const METRIC_THEME_DATA_BLOCK_FONT_CLASSES = {
  TITLE: `${METRIC_THEME_FONT_WEIGHT_CLASSES.SECONDARY} ${METRIC_THEME_FONT_COLOR_CLASSES.SECONDARY} ${METRIC_THEME_DATA_BLOCK_FONT_PROPERTY_CLASSES.HEADER}`,
  METRIC: `${METRIC_THEME_FONT_WEIGHT_CLASSES.PRIMARY} ${METRIC_THEME_FONT_COLOR_CLASSES.PRIMARY} ${METRIC_THEME_DATA_BLOCK_FONT_PROPERTY_CLASSES.CONTENT}`,
  SUB_TEXT: `${METRIC_THEME_FONT_WEIGHT_CLASSES.SECONDARY} ${METRIC_THEME_FONT_COLOR_CLASSES.SECONDARY} ${METRIC_THEME_DATA_BLOCK_FONT_PROPERTY_CLASSES.FOOTER}`,
};