export default (getColor, 
  METRIC_THEME_CHART_PALETTE_COLORS, 
  isLegendHidden = false,
  symbol = "square") => ({
  keys: ["tests"],
  sortByValue: true,
  innerRadius: .5,
  sliceLabelsSkipAngle: 10,
  sliceLabelsTextColor: "#ffffff",
  margin: { top: 40, right: 20, bottom: 10, left: 20 },
  arcLinkLabelsStraightLength:10,
  arcLinkLabelsDiagonalLength:10,
  colors: [
    METRIC_THEME_CHART_PALETTE_COLORS.CHART_PALETTE_COLOR_1,
    METRIC_THEME_CHART_PALETTE_COLORS.CHART_PALETTE_COLOR_2,
    METRIC_THEME_CHART_PALETTE_COLORS.CHART_PALETTE_COLOR_3,
    METRIC_THEME_CHART_PALETTE_COLORS.CHART_PALETTE_COLOR_4,
    METRIC_THEME_CHART_PALETTE_COLORS.CHART_PALETTE_COLOR_5,
  ],
  legends: [
    {
      anchor: "top-right",
      direction: "column",
      justify: false,
      translateX: 0,
      translateY: -30,
      itemsSpacing: 0,
      itemDirection: "right-to-left",
      itemWidth: 80,
      itemHeight: 20,
      itemOpacity: isLegendHidden ? 0 : 1,
      symbolSize: 10,
      symbolShape: symbol,
      symbolBorderColor: "rgba(0, 0, 0, .5)",
    },
  ],        
});