export const GIT_TO_GIT_SYNC_METRIC_CONSTANTS = {};

GIT_TO_GIT_SYNC_METRIC_CONSTANTS.SUPPORTED_DATA_POINT_IDENTIFIERS = {
  BASE_KPI_AVERAGE_EXECUTION_TIME_DATA_POINT: "base-kpi-average-execution-time-data-point",
};
