export const JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPES = {
  MAVEN: "Maven",
  NUGET: "NuGet",
  GENERIC: "Generic",
};

export const JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPE_LABELS = {
  MAVEN: "Maven",
  NUGET: "NuGet",
  GENERIC: "Generic",
};

export const getJfrogArtifactoryMavenPackageTypeLabel = (packageType) => {
  switch (packageType) {
    case JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPES.MAVEN:
      return JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPE_LABELS.MAVEN;
    case JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPES.NUGET:
      return JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPE_LABELS.NUGET;
    case JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPES.GENERIC:
      return JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPES.GENERIC;
    default:
      return packageType;
  }
};

export const JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPE_SELECT_OPTIONS = [
  {
    text: JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPE_LABELS.MAVEN,
    value: JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPES.MAVEN,
  },
  {
    text: JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPE_LABELS.NUGET,
    value: JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPES.NUGET,
  },
  {
    text: JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPE_LABELS.GENERIC,
    value: JFROG_ARTIFACTORY_MAVEN_PACKAGE_TYPES.GENERIC,
  },
];
