export const JIRA_CHANGE_FAILURE_RATE_CONSTANTS = {};

JIRA_CHANGE_FAILURE_RATE_CONSTANTS.SUPPORTED_DATA_POINT_IDENTIFIERS = {
  CHANGE_FAILURE_RATE_DATA_POINT: "jira-change-failure-rate-datapoint"
};
