export const GITLAB_PIPELINE_STATISTICS_CONSTANTS = {};

GITLAB_PIPELINE_STATISTICS_CONSTANTS.SUPPORTED_DATA_POINT_IDENTIFIERS = {
  PIPELINE_STATISTICS_DATA_POINT: "pipeline-statistics-data-point"
};