import React from "react";
import RoleAccessEditorHelpOverlayContainer from "components/common/help/input/role_access_editor/RoleAccessEditorHelpOverlayContainer";
import HelpOverlayBase from "components/common/overlays/center/help/HelpOverlayBase";

function PipelineWizardRuleInputHelpDocumentation() {
  return (
    <div className={"mt-2"}>
      <div className={"mb-2"}>
        <div><b>Pipeline Wizard Rule Filters</b></div>
        <div>This allows you to select which components will be included or excluded in this pipeline run.</div>
        <div>The rule order does not matter.</div>
        <div>
          <div className={"mt-3"}><b>Include Rules</b></div>
          <div className={"ml-3"}>
            <div>Include Rules specify what components are included.</div>
            <div>If no include rules are written, it includes all component types.</div>
            <div>If you only specify component types when writing an include rule, it assumes you want all files of that component type.</div>
            <div>If you specify field and assign values when writing an include rule, it includes only those that match those values.</div>
            <div>These rules are not exclusive. If it matches any include rule, it will be included in the initial data list.</div>
          </div>
        </div>
        <div>
          <div className={"mt-3"}><b>Exclude Rules</b></div>
          <div className={"ml-3"}>
            <div>Exclude Rules specify what components are excluded after building the initial list from include rules or the entire data set.</div>
            <div>If no exclude rules are written, the entire list generated by include rules is included.</div>
            <div>If you only specify component types when writing an exclude rule, it excludes all of that component type.</div>
            <div>If you specify field and assign values when writing an exclude rule, it excludes only those that match those values.</div>
            <div>These rules are not exclusive. If it matches any exclude rule, it will be excluded in the final data list.</div>
          </div>
        </div>
        <div>
          <div className={"mt-3"}><b>Overview</b></div>
          <div className={"ml-3"}>
            <div><b>If include rules are included:</b></div>
            <div className={"ml-2"}>
              <div>The initial list is built based on the include rules written.</div>
              <div>This list is then filtered by any exclude rules that exist. Exclude rules take precedence over any include rule.</div>
            </div>
            <div><b>If include rules are not included:</b></div>
            <div className={"ml-2"}>
              <div>If any exclude rules exist, the entire data set is filtered by those exclude rules.</div>
              <div>If no exclude rules exist, the entire data set is included.</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default React.memo(PipelineWizardRuleInputHelpDocumentation);