export const GITLAB_DEPLOYMENT_FREQUENCY_CONSTANTS = {};

GITLAB_DEPLOYMENT_FREQUENCY_CONSTANTS.SUPPORTED_DATA_POINT_IDENTIFIERS = {
  DEPLOYMENT_FREQUENCY_DATA_POINT: "deployment-frequency-data-point"
};